spring.application.name=demo
spring.h2.console.enabled=false
spring.h2.console.settings.web-allow-others=true
spring.datasource.url=jdbc:postgresql://db:5432/demo_db
spring.datasource.username=root
spring.datasource.password=Password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect