-- 既存テーブル (再起動時に破壊しないよう IF NOT EXISTS)
CREATE TABLE IF NOT EXISTS users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nickname VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS shops (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL UNIQUE,
    price      DECIMAL(10,2),
    stock      INTEGER DEFAULT 0,
    image_path VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- チャット用テーブル
CREATE TABLE IF NOT EXISTS user_profiles (
    user_id      BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    display_name VARCHAR(100),
    bio          VARCHAR(500),
    avatar_path  VARCHAR(255),
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_rooms (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100),
    type       VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_room_members (
    room_id   BIGINT REFERENCES chat_rooms(id) ON DELETE CASCADE,
    user_id   BIGINT REFERENCES users(id) ON DELETE CASCADE,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (room_id, user_id)
);

CREATE TABLE IF NOT EXISTS messages (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id   BIGINT REFERENCES chat_rooms(id) ON DELETE CASCADE,
    sender_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    content   VARCHAR(2000) NOT NULL,
    sent_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
